In [ ]:
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import glob



data_aug_gen = ImageDataGenerator(rotation_range=360, # 0~ 360도사이 임의의 각도로 회전
                                  width_shift_range=0.1, # 원본이미지 0.1픽셀 내외로 좌우이동
                                  height_shift_range=0.1, # 원본이미지 0.1픽셀 내외로 상하이동
                                  shear_range=0.1, # X라디안 시계반대방향으로 밀림강도 범위내에서 원본이미지 변경
                                  zoom_range= 0.2, # 확대(1+X)/축소(1-X)
                                  horizontal_flip=True,#수평방향 뒤집기
                                  vertical_flip=True,#수직방향 뒤집기
                                  fill_mode='nearest')

file=glob.glob("C:/Users/user/PycharmProjects/donghwi/donghwikim/code/OCT2017/train/make_img/" + "*")

for l ,f in enumerate(file):
    img = load_img(f)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    print(f + "변형된 이미지 생성")
    count=0
    for batch in data_aug_gen.flow(x, save_to_dir='D:/YoonHwan/make_img/', save_prefix='remake_1', save_format='jpeg'):
        count += 1
        if count > 1:
            break

In [10]:
from PIL import Image
import numpy as np

img = Image.open("D:/OCT-Image/make_dataset/train/CNV/CNV-103044-130.jpeg")
img = img.convert("RGB")
img = img.resize((299, 299))
data = np.asarray(img)

print(data)

[[[255 255 255]
  [ 82  82  82]
  [ 26  26  26]
  ...
  [254 254 254]
  [253 253 253]
  [253 253 253]]

 [[255 255 255]
  [ 86  86  86]
  [ 37  37  37]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [ 60  60  60]
  [ 29  29  29]
  ...
  [112 112 112]
  [118 118 118]
  [111 111 111]]

 ...

 [[253 253 253]
  [255 255 255]
  [255 255 255]
  ...
  [  7   7   7]
  [  6   6   6]
  [  6   6   6]]

 [[254 254 254]
  [252 252 252]
  [254 254 254]
  ...
  [  0   0   0]
  [  8   8   8]
  [ 12  12  12]]

 [[253 253 253]
  [255 255 255]
  [251 251 251]
  ...
  [  3   3   3]
  [ 13  13  13]
  [ 13  13  13]]]


In [13]:
img2 = Image.open("D:/OCT-Image/remake_img/DME/remake_DME_0_0.jpeg")
img2 = img2.convert("RGB")
img2 = img2.resize((299, 299))
data2 = np.asarray(img2)

print(data2)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 11  11  11]
  [ 12  12  12]
  [  8   8   8]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 11  11  11]
  [ 12  12  12]
  [  8   8   8]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 11  11  11]
  [ 12  12  12]
  [  8   8   8]]

 ...

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [  8   8   8]
  [  4   4   4]
  [  2   2   2]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [  7   7   7]
  [  6   6   6]
  [  7   7   7]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  4   4   4]
  [  4   4   4]
  [  6   6   6]]]
